#
# Module manifest for module 'DiskToAzureBlobStorage'
#
# Generated by: Vetle Kise
#
# Generated on: 01.01.2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'DiskToAzureBlobStorage.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = 'e6b9d2f9-4a3c-45d6-b2d4-1cfb2c3176b9'

    # Author of this module
    Author = 'Vetle Kise'

    # Company or vendor of this module
    CompanyName = 'Unknown'

    # Copyright statement for this module
    Copyright = '(c) Vetle Kise. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'A PowerShell module that uploads files, including a log and metadata file, to Azure Blob Storage.'

    # Minimum version of the PowerShell engine required by this module
    # PowerShellVersion = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @('Az.Storage')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'Copy-DiskToAzureBlobStorage'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}